name: Update Earnings Calendar

permissions:
  contents: write  # allow GITHUB_TOKEN to commit & push

on:
  schedule:
    - cron: '0 2 * * *'   # 10:00 Beijing Time
    - cron: '0 14 * * *'  # 22:00 Beijing Time
  workflow_dispatch:      # allow manual trigger


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🔧 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 📦 Install deps
        run: |
          pip install -r requirements.txt

      - name: 🚀 Generate ICS
        env:
          FINNHUB_TOKEN: ${{ secrets.FINNHUB_TOKEN }}
        run: |
          python scripts/generate_calendar.py

      - name: 📤 Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            git add earnings_calendar.ics
            git commit -m "chore: refresh earnings calendar [skip ci]"
            git push
          fi
